chmod: cannot access '/vanilla1.out': No such file or directory
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
Tue Apr 23 11:58:25 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    On   | 00000000:D2:00.0 Off |                  Off |
| 41%   35C    P8    14W / 140W |      1MiB / 16376MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
/orion/u/yiqingl/envs/gaufre/bin/python
/orion/u/yiqingl/envs/gaufre/bin/pip
True
2.2.1+cu118
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/torch/backends/cudnn/__init__.py", line 82, in version
    if not _init():
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/torch/backends/cudnn/__init__.py", line 58, in _init
    raise RuntimeError(
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 4, 1). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN. Looks like your LD_LIBRARY_PATH contains incompatible version of cudnn. Please either remove it from the path or install cudnn (8, 7, 0)
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 8
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_adv_train.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_adv_infer.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_cnn_train.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_cnn_infer.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_ops_infer.so.8
/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/nvidia/cudnn/lib/libcudnn_ops_train.so.8
Using /orion/u/yiqingl/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /orion/u/yiqingl/.cache/torch_extensions/diff_gaussian_rasterization/build.ninja...
Building extension module diff_gaussian_rasterization...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module diff_gaussian_rasterization...
Using /orion/u/yiqingl/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /orion/u/yiqingl/.cache/torch_extensions/diff_gaussian_rasterization_4dch9/build.ninja...
Building extension module diff_gaussian_rasterization_4dch9...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module diff_gaussian_rasterization_4dch9...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA RTX A4000') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/orion/u/yiqingl/GaussianDiff'
To add an exception for this directory, call:

	git config --global --add safe.directory /orion/u/yiqingl/GaussianDiff'
git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/orion/u/yiqingl/GaussianDiff'
To add an exception for this directory, call:

	git config --global --add safe.directory /orion/u/yiqingl/GaussianDiff'
wandb: Currently logged in as: lynl7130. Use `wandb login --relogin` to force relogin
wandb: WARNING Path ./output/hypernerf/split-cookie/TRBF/vanilla1/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path ./output/hypernerf/split-cookie/TRBF/vanilla1/wandb/ wasn't writable, using system temp directory
wandb: wandb version 0.16.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.5
wandb: Run data is saved locally in /tmp/mikacuy/wandb/run-20240423_115922-wzn2jfbo
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run TRBF_vanilla1_fit
wandb: ‚≠êÔ∏è View project at https://wandb.ai/lynl7130/GaussianDiff_hypernerf
wandb: üöÄ View run at https://wandb.ai/lynl7130/GaussianDiff_hypernerf/runs/wzn2jfbo/workspace
output path: ./output/hypernerf/split-cookie/TRBF/vanilla1
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
0it [00:00, ?it/s]135it [00:00, 68269.96it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name         | Type      | Params
-------------------------------------------
0 | rgbdecoder   | Sandwich  | 90    
1 | deform_model | TRBFModel | 0     
2 | lpips        | LPIPS     | 2.5 M 
  | other params | n/a       | 26.9 M
-------------------------------------------
26.9 M    Trainable params
2.5 M     Non-trainable params
29.4 M    Total params
117.486   Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
Number of points at initialisation :  20075
Sanity Checking: |          | 0/? [00:00<?, ?it/s]Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]python: symbol lookup error: /orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_cnn_infer.so.8: undefined symbol: _Z20traceback_iretf_implPKcRKN5cudnn16InternalStatus_tEb, version libcudnn_ops_infer.so.8
Using /orion/u/yiqingl/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /orion/u/yiqingl/.cache/torch_extensions/diff_gaussian_rasterization/build.ninja...
Building extension module diff_gaussian_rasterization...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module diff_gaussian_rasterization...
Using /orion/u/yiqingl/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /orion/u/yiqingl/.cache/torch_extensions/diff_gaussian_rasterization_4dch9/build.ninja...
Building extension module diff_gaussian_rasterization_4dch9...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module diff_gaussian_rasterization_4dch9...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA RTX A4000') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/orion/u/yiqingl/GaussianDiff'
To add an exception for this directory, call:

	git config --global --add safe.directory /orion/u/yiqingl/GaussianDiff'
git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/orion/u/yiqingl/GaussianDiff'
To add an exception for this directory, call:

	git config --global --add safe.directory /orion/u/yiqingl/GaussianDiff'
wandb: Currently logged in as: lynl7130. Use `wandb login --relogin` to force relogin
wandb: WARNING Path ./output/hypernerf/split-cookie/TRBF/vanilla1/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path ./output/hypernerf/split-cookie/TRBF/vanilla1/wandb/ wasn't writable, using system temp directory
wandb: wandb version 0.16.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.5
wandb: Run data is saved locally in /tmp/mikacuy/wandb/run-20240423_115949-3cse5ov5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run TRBF_vanilla1_test
wandb: ‚≠êÔ∏è View project at https://wandb.ai/lynl7130/GaussianDiff_hypernerf
wandb: üöÄ View run at https://wandb.ai/lynl7130/GaussianDiff_hypernerf/runs/3cse5ov5/workspace
output path: ./output/hypernerf/split-cookie/TRBF/vanilla1
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
0it [00:00, ?it/s]135it [00:00, 69724.30it/s]
Restoring states from the checkpoint path at ./output/hypernerf/split-cookie/TRBF/vanilla1/checkpoints/last.ckpt
Number of points at initialisation :  20075
Traceback (most recent call last):
  File "/orion/u/yiqingl/GaussianDiff/main.py", line 6, in <module>
    cli = MyLightningCLI(
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 754, in test
    return call._call_and_handle_interrupt(
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 956, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 397, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 79, in resume_start
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 368, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "/orion/u/yiqingl/envs/gaufre/lib/python3.9/site-packages/lightning/fabric/plugins/io/torch_io.py", line 81, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint file not found: {path}")
FileNotFoundError: Checkpoint file not found: ./output/hypernerf/split-cookie/TRBF/vanilla1/checkpoints/last.ckpt
wandb: - 0.011 MB of 0.011 MB uploadedwandb: \ 0.011 MB of 0.016 MB uploadedwandb: | 0.016 MB of 0.016 MB uploadedwandb: üöÄ View run TRBF_vanilla1_test at: https://wandb.ai/lynl7130/GaussianDiff_hypernerf/runs/3cse5ov5/workspace
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /tmp/mikacuy/wandb/run-20240423_115949-3cse5ov5/logs
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/debug-internal.log': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/latest-run': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/debug.log': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/tmp/code': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/wandb-summary.json': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/output.log': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/config.yaml': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/39_1_4b282371d695cfedc121.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/10_0_0e61d59b293bd47f5893.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/10_0_d14a070ce86ad91d4752.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/39_1_49021c96f8c2e94546cc.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/39_1_234e1d2284c3ce40c920.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/39_1_718d34db1d5541203e8a.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/10_0_215dbcfe45858eea548f.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/media/images/val_images_train/10_0_718d34db1d5541203e8a.png': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/conda-environment.yaml': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/wandb-metadata.json': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/files/requirements.txt': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/run-v2xuepz2.wandb': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/logs/debug-internal.log': Permission denied
rm: cannot remove './output/hypernerf/split-cookie/TRBF/vanilla1/wandb/run-20240422_192106-v2xuepz2/logs/debug.log': Permission denied
chmod: cannot access '/vanilla1.out': No such file or directory
